version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: travel_agency
      MYSQL_USER: traveluser
      MYSQL_PASSWORD: travelpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=db
      - DB_USER=traveluser
      - DB_PASSWORD=travelpassword
      - DB_NAME=travel_agency
    ports:
      - "5000:5000" # api port 5000 express
    depends_on:
      - db

volumes:
  db_data:
