name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm run test:run

      - name: Build project
        run: npm run build
